# Generated by Django 5.1.4 on 2024-12-28 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="createdAt",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 28, 9, 44, 36, 600227)
            ),
        ),
    ]
