# Generated by Django 5.1.4 on 2024-12-28 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0002_alter_volunteer_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="createdAt",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 28, 9, 52, 5, 863157)
            ),
        ),
    ]
