# Generated by Django 5.1.4 on 2024-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0004_alter_volunteer_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="createdAt",
            field=models.DateTimeField(),
        ),
    ]
