# Generated by Django 5.1.4 on 2024-12-28 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0008_alter_volunteer_createdat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="createdAt",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 28, 15, 40, 25, 302611, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
