# Generated by Django 5.1.4 on 2024-12-28 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0009_alter_volunteer_createdat_alter_volunteer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
